apiVersion: 1

datasources:
  - name: InfluxDB_v2_Flux
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: tfg
      defaultBucket: mainnet
      tlsSkipVerify: true
    secureJsonData:
      token: ae5cdaf02c215b9056ca31e5e8efd0ef231a9dcc3a3649f09b635bfedd70626c