version: "3.8"

services:
  influxdb:
    image: influxdb:alpine
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:8086

  telegraf:
    image: telegraf_ethereum:latest
    volumes:
      - ${TELEGRAF_CFG_PATH}:/etc/telegraf/telegraf.conf
      - ${TELEGRAF_SCRIPT_PATH}:/opt/scripts
    env_file:
      - .env
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana
    volumes:
      - grafana-storage:/var/lib/grafana:rw
      - ${GRAFANA_DATASOURCE_PATH}:/etc/grafana/provisioning/datasources/datasource.yaml
    env_file:
      - .env
    depends_on:
      - influxdb
    ports:
      - ${GRAFANA_PORT}:3000
  
  loki:
    image: grafana/loki:latest
    ports:
      - ${LOKI_PORT}:3100
    volumes:
      - ${LOKI_CFG_PATH}:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml

  alloy:
    image: grafana/alloy:latest
    ports:
      - ${ALLOY_PORT}:12345
    volumes:
      - ${ALLOY_CFG_PATH}:/etc/alloy/config.alloy
      - ${ALLOY_LOGS_PATH}:/tmp/app-logs/
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    depends_on:
      - loki

volumes:
  grafana-storage:
  influxdb-storage:
